sudo: required
cache: bundler
services:
  - docker
env:
  global:
    - TESTOPTS="-v"
    - TINYTDS_UNIT_HOST=localhost
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
before_install:
  - export PATH=/opt/local/bin:$PATH
  - docker info
  - sudo ./test/bin/setup.sh
install:
  - export PATH=/opt/local/bin:$PATH
  - gem install bundler
  - bundle --version
  - bundle install
  - bundle exec rake ports
script:
  - bundle exec rake build test
